import { MappedHouseProduct } from "./types/types";

export const MOCKED_MAPPED_DATA: MappedHouseProduct = {
  publicationDate: "2023-01-01",
  bathrooms: 2,
  rooms: 5,
  bedrooms: 3,
  floors: "2",
  objectType: "Apartment",
  address: "123 Example Street",
  vveContribution: null,
  constructionYear: "2015",
  boilerInfo: "Energy-efficient boiler",
  tagline: {
    HasPromotionLabel: true,
    PromotionLabelType: 1,
    RibbonColor: 0,
    RibbonText: null,
    Tagline: "Modern living",
  },
  energyLabel: {
    Definitief: true,
    Index: null,
    Label: "A",
    NietBeschikbaar: false,
    NietVerplicht: false,
  },
  mainPhoto: "https://picsum.photos/300",
  id: 1,
  rented: false,
  sold: false,
  insulation: "High-quality",
  summary: {
    Ad: null,
    Kenmerken: [],
    LokNummer: 1,
    SubKenmerk: null,
    Titel: null,
  },
  location: "City Center",
  realtor: { name: "Realtor Name", id: 123, phone: "123-456-7890" },
  mediaPhotos: [
    "https://picsum.photos/id/42/1920/1080",
    "https://picsum.photos/id/49/1920/1080",
    "https://picsum.photos/id/163/1920/1080",
    "https://picsum.photos/id/257/1920/1080",
    "https://picsum.photos/id/288/1920/1080",
    "https://picsum.photos/id/369/1920/1080",
  ],
  landArea: 150,
  city: "Sample City",
  postcode: "1234 AB",
  price: {
    GeenExtraKosten: null,
    HuurAbbreviation: "",
    Huurprijs: null,
    HuurprijsOpAanvraag: "",
    HuurprijsTot: null,
    KoopAbbreviation: "€",
    Koopprijs: 450000,
    KoopprijsOpAanvraag: "",
    KoopprijsTot: 450000,
    OriginelePrijs: null,
    VeilingText: "",
  },
  saleStatus: "Beschikbaar",
  heating: "Central Heating",
  description: "Beautiful apartment located in the heart of the city.",
  gardenLocation: "South",
  mapCoordinates: { lat: 52.3791, lng: 4.9003 },
  livingArea: 100,
  parkingType: "Garage",
  viewingCalendar: true,
  brochureDownload: true,
};
